title: "Yousef Yousefi"
description: "Official website of Yousef Yousefi - Researcher and Scientist."
theme: jekyll-theme-cayman
markdown: kramdown

# Navigation links in the header
header_pages:
  - index.md
  - about.md
  - contact.md
  - table of contents.md
  
# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: social links (can improve SEO)
social_links:
  - name: GitHub
    url: https://sgh-paradigm.github.io/Yousef-Yousefi/
  - name: ResearchGate
    url: https://www.researchgate.net/profile/Yousef-Yousefi-7
  - name: Email
    url: mailto:yousefyousefi606@gmail.com

# GitHub repository settings (optional)
repository: SGH-paradigm/Yousef-Yousefi

# Other settings
show_downloads: false
