# _config.yml

title: "Yousef Yousefi"
description: "Official Website of Yousef Yousefi"
url: "https://sgh-paradigm.github.io/Yousef-Yousefi"
baseurl: "" # Important: empty if your repo name matches username/repo

theme: just-the-docs

color_scheme: light

# Optional settings to make it more professional
search_enabled: true
aux_links:
  "View GitHub Repository":
    - "https://github.com/SGH-paradigm/Yousef-Yousefi"

# Logo or favicon if you have it later
favicon_ico: "/favicon.ico"

# Navigation Order Settings
nav_sort: case_insensitive
