title: "Yousef Yousefi"
description: "Official website of Yousef Yousefi - Researcher and Scientist."
theme: jekyll-theme-cayman
markdown: kramdown

header_pages:
  - index.md
  - about.md
  - table-of-contents.md
  - contact.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

social_links:
  - name: GitHub
    url: https://sgh-paradigm.github.io/Yousef-Yousefi/
  - name: ResearchGate
    url: https://www.researchgate.net/profile/Yousef-Yousefi-7
  - name: Email
    url: mailto:yousefyousefi606@gmail.com

repository: SGH-paradigm/Yousef-Yousefi

show_downloads: false
