title: "Science Generalization Hypothesis (SGH)"
description: "Official website of Yousef Yousefi's lifelong interdisciplinary scientific research."
baseurl: "/Yousef-Yousefi" # Keep this if your GitHub repo is named Yousef-Yousefi
url: "https://sgh-paradigm.github.io"

theme: minima

header_pages:
  - index.md
  - table-of-contents.md
  - contact.md
  - support-the-mission.md
  - feedback.md
  - license.md

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

permalink: pretty
